export const PRODUCTS = [
  {
    id: "#1",
    name: "Feijoada completa",
    desc: "Feijão preto com carnes nobres, arroz, farofa crocante e couve refogada.",
    price: "R$ 42,00",
    category: { label: "Pratos brasileiros", emoji: "🍛" },
    status: "Disponível",
    img: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?q=80&w=200&auto=format&fit=crop",
  },
  {
    id: "#2",
    name: "Moqueca de camarão",
    desc: "Caldo de dendê com camarão, pimentões, coentro fresco e arroz branco.",
    price: "R$ 58,00",
    category: { label: "Frutos do mar", emoji: "🦐" },
    status: "Disponível",
    img: "https://images.unsplash.com/photo-1612874472278-5c1f9c8b33a6?q=80&w=200&auto=format&fit=crop",
  },
  {
    id: "#3",
    name: "Pão de queijo recheado",
    desc: "Massa mineira com queijo meia cura e recheio cremoso de requeijão.",
    price: "R$ 9,50",
    category: { label: "Salgados e lanches", emoji: "🥟" },
    status: "Disponível",
    img: "https://images.unsplash.com/photo-1484723091739-30a097e8f929?q=80&w=200&auto=format&fit=crop",
  },
  {
    id: "#4",
    name: "Coxinha de frango",
    desc: "Clássica de frango com catupiry, massa crocante e tempero caseiro.",
    price: "R$ 11,00",
    category: { label: "Salgados e lanches", emoji: "🥟" },
    status: "Disponível",
    img: "https://images.unsplash.com/photo-1543353071-087092ec393e?q=80&w=200&auto=format&fit=crop",
  },
  {
    id: "#5",
    name: "Churrasco misto",
    desc: "Picanha, linguiça artesanal, pão de alho e vinagrete na brasa.",
    price: "R$ 74,00",
    category: { label: "Churrasco", emoji: "🥩" },
    status: "Disponível",
    img: "https://images.unsplash.com/photo-1561758033-d89a9ad46330?q=80&w=200&auto=format&fit=crop",
  },
  {
    id: "#6",
    name: "Escondidinho de carne seca",
    desc: "Purê de mandioca com carne seca desfiada, queijo gratinado e cebolinha.",
    price: "R$ 36,00",
    category: { label: "Pratos brasileiros", emoji: "🍛" },
    status: "Indisponível",
    img: "https://images.unsplash.com/photo-1604908176997-431579f4d7b5?q=80&w=200&auto=format&fit=crop",
  },
  {
    id: "#7",
    name: "Pastel de feira",
    desc: "Pastel grande de queijo coalho com molho de pimenta doce.",
    price: "R$ 14,00",
    category: { label: "Salgados e lanches", emoji: "🥟" },
    status: "Disponível",
    img: "https://images.unsplash.com/photo-1528715471579-d1bcf0ba5e83?q=80&w=200&auto=format&fit=crop",
  },
  {
    id: "#8",
    name: "Açaí na tigela",
    desc: "Açaí batido com banana, granola, mel e castanhas torradas.",
    price: "R$ 23,00",
    category: { label: "Sucos e gelados", emoji: "🥤" },
    status: "Disponível",
    img: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?q=80&w=200&auto=format&fit=crop",
  },
  {
    id: "#9",
    name: "Brigadeiro de colher",
    desc: "Brigadeiro cremoso 70% cacau servido no pote, com granulado belga.",
    price: "R$ 8,00",
    category: { label: "Sobremesas", emoji: "🍰" },
    status: "Disponível",
    img: "https://images.unsplash.com/photo-1505253758473-96b7015fcd40?q=80&w=200&auto=format&fit=crop",
  },
  {
    id: "#10",
    name: "Café coado gourmet",
    desc: "Blend brasileiro com notas de chocolate, coado na hora e servido quente.",
    price: "R$ 7,50",
    category: { label: "Cafés e quentes", emoji: "☕" },
    status: "Em revisão",
    img: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?q=80&w=200&auto=format&fit=crop",
  },
];

export const TOTAL_PRODUCTS = 79;
export const PAGE = 1;
export const TOTAL_PAGES = 8;
